### ISSUE TITLE
Transparent .gauge-frame

### ISSUE THREAD

**Issue by jmw6773** [custom-cards/dual-gauge-card#13]
When using a theme that has  '--paper-card-background-color' set with a transparent color causes the dual-gauge-card to double the background color on the gauge-frame element of the card. This causes the overall transparency of the card to be half of the expected value.

Is the 'background-color' definition required in the [.gauge-frame (::256) block](https://github.com/Rocka84/dual-gauge-card/blob/c27416b15d3861a55f70a2eb312dc9e42e69b134/dual-gauge-card.js#L256) of the CSS file? 
Or could the frame background-color be a settable option for the card?

**Comment by Rocka84** [comment]
Hi,
sorry for the delay.
As I remember, that css rule was necessary. But I can definetly make this an option for the card.

**Comment by Rocka84** [comment]
Seems you were right, that css rule was redundant :grin: 
Thanks for pointing out!

If you still wish an option for the background color, feel free to open another issue.
