### ISSUE TITLE
Custom-Updater support

### ISSUE THREAD

**Issue by johntdyer** [custom-cards/dual-gauge-card#14]
Possible to make this supported by custom-updater so we can keep things up to date if we install it ?

**Comment by Rocka84** [comment]
Hi!
Today I joined the [custom-cards organization](https ://github.com/custom-cards) :tada:
This also means, this card is now available through [HACS](https://github.com/custom-components/hacs). 

Thanks for reminding me :wink:

**Comment by fortepc** [comment]
@Rocka84 speaking of being available through HACS... 

https://i.imgur.com/IIYiqUG.png

![image](https://user-images.githubusercontent.com/26149601/62669895-532cfe00-b95f-11e9-9f29-e06906d649b6.png)

**Comment by Rocka84** [comment]
Thanks for letting me know! I opened a new issue and will fix this as soon as I can.
But please be patient, RL is keeping me busy atm. I'm accepting pull requests by the way ;-)
