### ISSUE TITLE
HACS could not determine the type of this element

### ISSUE THREAD

**Issue by Rocka84** [custom-cards/dual-gauge-card#16]
As @fortepc stated in #14, support for HACS seems to be broken. 

See https://github.com/custom-cards/dual-gauge-card/issues/14#issuecomment-519333673

**Comment by Rocka84** [comment]
After having a closer look at this, I see this as an enhancement, not a bug. Installation via HACS works fine, it just doesn't tell you that this is of `type: js`.  
I'll add a note to the readme until I figure out how to become fully compatible with HACS.

**Comment by bepstein111** [comment]
![Screenshot_2019-11-04_17-20-19](https://user-images.githubusercontent.com/6173863/68162995-654f1600-ff27-11e9-81ec-63ce5dd4c7c6.png)
Not sure if related, or if I'm a big dummy, but after installing via HACS, it's not liking anything I put for type.

**Comment by KTibow** [comment]
It's not adding an error for me, try manually adding `/hacsfiles/dual-gauge-card/dual-gauge-card.js`. Time to close?

**Comment by bepstein111** [comment]
Don't remember how, but I figured my thing out, turns out I was just being a big dummy

**Comment by marmao78** [comment]
I install HACS, install dual-gauge frontend, and try to add url and type in all places in ui-lovelace file. Still not working.
Maybe I´m doing something wrong, please help. I´m facing the following error.
Value is not accepted, Valid values: "iframe"
![error](https://user-images.githubusercontent.com/76015234/102391661-c6fc0380-3fb4-11eb-84ec-1a1390d8e34d.png)

**Comment by KTibow** [comment]
You’re putting the config to load dual gauge card where you’re supposed to put the config to configure it. Use `type: custom:dual-gauge-card`, and read the docs.

**Comment by marmao78** [comment]
In the instructions, it mentions adding the following information in the ui-lovelace.yaml
  - url: /community_plugin/dual-gauge-card/dual-gauge-card.js
    type: js

But I´m not sure where to add these commands?
If I add in the beginning of ui-locelace.yaml it shows the following error:
![error2](https://user-images.githubusercontent.com/76015234/102399732-c5840880-3fbf-11eb-98d9-0cff96fa5469.png)

If I add the commands included in the card configuration it shows the first error.

But both of them show the following error when I try to refresh the screen.
![error3](https://user-images.githubusercontent.com/76015234/102400272-6ffc2b80-3fc0-11eb-83b6-d6d571a45a66.png)

I will be glad if you can share an example where do I add these commands?

**Comment by marmao78** [comment]
I finally found the issue.
In configuration.YAML you should add on top the following information bellow.  

lovelace:
  mode: yaml
  resources:
    - url: /local/community/dual-gauge-card/dual-gauge-card.js
      type: css


The instruction tells me to use type: js, but I always got an error. So I use type: css and it works.

**Comment by KTibow** [comment]
What error do you get? It's definitely not CSS, JS should work.

**Comment by marmao78** [comment]
Sorry. I used type: module.
I correct my comment on the top.
The error that I was facing is on comments on top.
When I use type: js, it shows an error (print screen on top). With type: module work just fine.
