### ISSUE TITLE
Doesn't Work on Mobile view

### ISSUE THREAD

**Issue by max-rh** [custom-cards/dual-gauge-card#18]
Hi,

Thanks for an amazing Card.
unfortunately it doesn't view on HA mobile.
Any idea why? it shows "Custom element doesnt exist"

Thanks

**Comment by Rocka84** [comment]
Hi!

Sorry I missed this issue for so long.
What exactly do you mean by "HA mobile"? The card should work fine on recent versions of chrome on android devices.

**Comment by RDoull** [comment]
hi, 

dunno what i am doing wrong, though installed from HACS onto current version of hass.io anf i get 

"Custom element doesn't exist: dual-gauge-card." 

added the following to my ui_lovelace.yaml 

  - url: /local/community/dual-gauge-card/dual-gauge-card.js
    type: js

could it be due to using Chrome?

**Comment by KTibow** [comment]
HACS automatically added it for me, if it wasn't auto-added for you add `/hacsfiles/dual-gauge-card/dual-gauge-card.js`.

**Comment by JCPvanHooren** [comment]
Actually, I installed this today and have the same issue...
On Android, using the HA Android App, it doesn't work and say:
`Custom element doesn't exist: dual-gauge-card`
It does work fine on Android Chrome as well as Desktop, Windows 10, Chrome.

**Comment by KTibow** [comment]
@JCPvanHooren clear cache/data and reload?

**Comment by JCPvanHooren** [comment]
Or wait 24hrs... it worked today, without making any changes.
Not sure if that's due to cache/data or something else, but it works now.

**Comment by Rocka84** [comment]
> Not sure if that's due to cache/data

Yes, it is :-)
