### ISSUE TITLE
Use state of object not working

### ISSUE THREAD

**Issue by viper71285** [custom-cards/dual-gauge-card#20]
I don't know if it is not supported or if I am just doing it wrong, but I been trying numerous ways of using the value of a sensor to determine the color for example

          colors:
            - color: var(--label-badge-red)
              value: '99'
            - color: var(--label-badge-green)
              value: '{{ states.sensor.bathroom_humidity_threshold.state }}'

where if the value of sensor.bathroom_humidity is higher sensor.bathroom_humidity_threshold it is red, and if its lower it will be green

**Comment by Rocka84** [comment]
Hi!
Sorry, using templates for color values is not supported as of now. I may consider implementing this in the future but I can't give any schedule on this.
