### ISSUE TITLE
cardwidth is changing the card's height

### ISSUE THREAD

**Issue by dacorn** [custom-cards/dual-gauge-card#21]
HI, I am trying to change the width of the card but when I change the value to cardwidth: 200 it changes the height and not the width. Be great if both were supported but I am fine if just width worked. Great card by the way this does exactly what I wanted.

**Comment by Rocka84** [comment]
Hi!
cardwith changes both the width and the height of the card. This is a known behaviour and is statet in the readme:
> All elements of the gauge are sized relative to this [cardwidth] so that the gauge scales to this [...]

I recently checked this and it did work my setup. If this isn't the case for you, please open a new issue and go into more detail.
