### ISSUE TITLE
Problem with Home Assistant 0.106

### ISSUE THREAD

**Issue by vencakratky** [custom-cards/dual-gauge-card#24]
Hello, after update 0.106 dual-gauge-card not working
![dual-gauge](https://user-images.githubusercontent.com/54419577/75386121-6bf00780-58e1-11ea-897d-8b00ba75feb8.png)

**Comment by nick2k3** [comment]
here too:
<img width="1002" alt="Schermata 2020-02-26 alle 22 54 46" src="https://user-images.githubusercontent.com/42848864/75391792-0b65c800-58eb-11ea-9cd3-da2ddebc193a.png">
Using version 0.5.1 on Home Assistant 0.106.0 .

**Comment by GitHubxtsnl** [comment]
same problem here.
`Cannot assign to read only property 'min' of object '#<Object>'
colors:
  - color: var(--label-badge-red)
    value: 40
  - color: var(--label-badge-yellow)
    value: 34
  - color: var(--label-badge-green)
    value: 27
  - color: var(--label-badge-blue)
    value: 20
  - color: var(--paper-blue-400)
    value: 0
inner:
  colors:
    - color: var(--label-badge-red)
      value: 40
    - color: var(--label-badge-yellow)
      value: 34
    - color: var(--label-badge-green)
      value: 27
    - color: var(--label-badge-blue)
      value: 20
    - color: var(--paper-blue-400)
      value: 0
  entity: sensor.work2home
  label: 2Home
  max: 60
  min: 0
  unit: min
max: 60
min: 1
outer:
  colors:
    - color: var(--label-badge-red)
      value: 40
    - color: var(--label-badge-yellow)
      value: 34
    - color: var(--label-badge-green)
      value: 27
    - color: var(--label-badge-blue)
      value: 20
    - color: var(--paper-blue-400)
      value: 0
  entity: sensor.home2work
  label: 2Work
  max: 60
  min: 1
  unit: min
shadeInner: true
title: Reistijd
type: 'custom:dual-gauge-card'`

**Comment by rhoppel** [comment]
![image](https://user-images.githubusercontent.com/1000765/75406717-d2bbf380-58d6-11ea-8cb0-c9cf6841f7ce.png)

I also get problems on all of my dual gauge instances. with 106.0

**Comment by coltonrb** [comment]
JS console confirms that line 22, where it attempts to assign a value to `this.config.min`, is the problem. Possibly related to [https://github.com/home-assistant/home-assistant-polymer/pull/4987](this frontend change?) Not quite sure - maybe someone with a bit more experience can chime in.

**Comment by tomlevels** [comment]
This is due to changes in version 0.106, also see https://github.com/custom-cards/dual-gauge-card/issues/22

**Comment by fudu** [comment]
I get same error and another...: Cannot assign to read only property '0' of object '[object Array]'
![Cattura](https://user-images.githubusercontent.com/6508171/75470924-b7fa8500-5991-11ea-90df-3c9a98b7ca1d.JPG)

**Comment by cerebrate** [comment]
Until there's an official fix out, per #22, you can replace line 19 of dual-gauge-card.js with

```
config = JSON.parse(JSON.stringify(config));
```

as a workaround.

**Comment by vencakratky** [comment]
> 
> 
> Until there's an official fix out, per #22, you can replace line 19 of dual-gauge-card.js with
> 
> ```
> config = JSON.parse(JSON.stringify(config));
> ```
> 
> as a workaround.

For me not working

**Comment by cerebrate** [comment]
You may also have to delete the dual-gauge-card.js.gz file to be sure your modification loads.

**Comment by rhoppel** [comment]
> ETA: oops, my bad. See my fixed version above.
> 
> You may also have to delete the dual-gauge-card.js.gz file to be sure your modification loads.

This works! Be sure to delete "dual-gauge-card.js.gz"

**Comment by rhoppel** [comment]
> Until there's an official fix out, per #22, you can replace line 19 of dual-gauge-card.js with
> 
> ```
> this.config = JSON.parse(JSON.stringify(config));
> ```
> 
> as a workaround.

This works!!!  Be sure to delete "**dual-gauge-card.js.gz** ".

**Comment by vencakratky** [comment]
So, i tried this: 
1.) edit /config/www/dual-gauge-card.js:
![configdual](https://user-images.githubusercontent.com/54419577/75486436-cd30dd00-59ac-11ea-931f-04c6fd81dde9.png)
2.) Download this edited file
3.) Via "File Editor" in HA delete dual-gauge-card.js
4.) Reload Core (in File Editor)
5.) Upload again edited file dual-guage-card.js to /config/www/dual-gauge-card.js
6.) Again Reload Core or Restart HA

Now dual-gauge-card are back ! :-) 
Please try somebody else this procedure. After i close this issue

**Comment by artaxx81** [comment]
No chance here, sorry! Tested it with HACS and manual installation (www and www/community folder)

There is no difference between before!

**Comment by owenostrander** [comment]
> 
> 
> So, i tried this:
> 1.) edit /config/www/dual-gauge-card.js:
> ![configdual](https://user-images.githubusercontent.com/54419577/75486436-cd30dd00-59ac-11ea-931f-04c6fd81dde9.png)
> 2.) Download this edited file
> 3.) Via "File Editor" in HA delete dual-gauge-card.js
> 4.) Reload Core (in File Editor)
> 5.) Upload again edited file dual-guage-card.js to /config/www/dual-gauge-card.js
> 6.) Again Reload Core or Restart HA
> 
> Now dual-gauge-card are back ! :-)
> Please try somebody else this procedure. After i close this issue

Your procedure worked for me, I have my card back! Thank-you.

**Comment by vencakratky** [comment]
There was still a problem with Home Assistant APP under iOS. You have to "Reset frontend cache" in Application setting and restart HA app

**Comment by hoburgt** [comment]
I updated yesterday evening and got the same error afterwards. This fix did the trick so thanks very much!!

**Comment by McGiverGim** [comment]
I tested the fix:
1. It works
2. If I write by mistake an entity name bad, the complete TAB does not load (not only the card). I don't know if this only happens to me or if this problem was there before.
3. The Android app had the same problem, I needed to erase all the data from the app to make it work (I have not seen the "Reset frontend cache" option in Android).

**Comment by ner0tic** [comment]
Upgraded to 0.106.1 last night from 1.105.x (i forget which, but the more recent) and also encounter this issue.  This  fix did not work for me.  I removed thegz file, cleared my cache, tried a "fresh" browser.

**Comment by ner0tic** [comment]
> Upgraded to 0.106.1 last night from 1.105.x (i forget which, but the more recent) and also encounter this issue. This fix did not work for me. I removed thegz file, cleared my cache, tried a "fresh" browser.

After some tinkering...
I changed the
`this.config = JSON.parse(JSON.stringify(config));`
to
`config = JSON.parse(JSON.stringify(config));`
and it worked.

**Comment by Lymkin** [comment]
None of the fixes above worked for me. Version 106.2

![has](https://user-images.githubusercontent.com/19554960/75611843-c22c9880-5ae3-11ea-8020-7e91163e107a.PNG)

**Comment by vencakratky** [comment]
If i try" config = JSON.parse(JSON.stringify(config));" , become error
![config](https://user-images.githubusercontent.com/54419577/75663932-f766f100-5c71-11ea-86ae-bf7e3b2a7baa.jpg)
![error](https://user-images.githubusercontent.com/54419577/75663937-f9c94b00-5c71-11ea-880b-0439d3f5e6ee.jpg)

**Comment by PonyOny** [comment]
On latest version if you set the top line as mentioned above
`this.config = JSON.parse(JSON.stringify(config));`
you will have to also remove this line as it's setting it again with the parameter and the new line you added would get overridden.
![image](https://user-images.githubusercontent.com/17080292/76172996-8fe20180-619b-11ea-892d-ca41359e36af.png)

**Comment by eugr** [comment]
BTW, if you have ssh access to HA, no need to delete the js.gz file. Just change to that directory and run `gzip -k dual-gauge-card.js`

Don't forget `-k` modifier otherwise it will delete the js file after compressing it into gz

**Comment by lebherz** [comment]
Will somebody push the fix to github?
so that we all get a new version?
thx!

**Comment by fmonday** [comment]
That fix works, thanks all!

**Comment by lebherz** [comment]
... now wait for merging..........................................................................

**Comment by lebherz** [comment]
Sorry @Rocka84  to contact you in office. We all try to get in contact with you :) and it was not transparent, that this Plugin was a private thing. I apologize! 

best regards 
rené

**Comment by Rocka84** [comment]
Hi!
This issue was fixed with #29, thanks again @lebherz 
@lebherz again: Apology accepted and sorry if I my answer was a bit harsh. After all you were right, I really should have taken more care of this project.
