### ISSUE TITLE
Big values overlap

### ISSUE THREAD

**Issue by PonyOny** [custom-cards/dual-gauge-card#26]
When displaying big values they overlap and card does not adapt & render properly
![image](https://user-images.githubusercontent.com/17080292/76173224-d46e9c80-619d-11ea-9f94-a426f7598026.png)

**Comment by Rocka84** [comment]
Hi!
Confirmed :-(
Unfortunaltely I have no idea how to fix this within the space constrains. Shrinking the font for example would make the values too small to read.
My only advise would be to drop the unit labels. Maybe you could integrate the unit in the card title, like `title: Speed in Mbps`.
I'll come back to this issue when I can think of a solution.

**Comment by dynasticorpheus** [comment]
@Rocka84  Perhaps you could add an option to have the values at the bottom instead of name which would already help a bit?

**Comment by ciaron23** [comment]
having the same troubles. I think adding the option of font styling would help :3

**Comment by KTibow** [comment]
Also, how about to put it on the top as well? Or instead of side-by-side then vertical.

**Comment by eode** [comment]
I think having the labels above/below each other instead of (or as well as) name might work nicely.

```
Rather than:
571.78  356.39
Down     Up
Speed Test

This could be
571.78 Down
356.39 Up
Speed Test
```

Also, people can round their values to reduce them somewhat.
Another option is to have the reading inside the progress bar for each one, centered (but text color would need to be settable, or calculated for contrast).

**Comment by saper-2** [comment]
Or maybe go for few solutions, so user can "pick what want", I'd add options:
- set font size for each gauge label (maybe custom colors depending on value)
- set precision of displayed number in label (this is what I basically would want the most 😄 )
- label layout: column(horizontal-stack)/line(vertical-stack)

If I could set precision to 0.1 (1 digit after comma) it would fit, or make the label stacked vertically ( layout: line(vertical) )
![obraz](https://user-images.githubusercontent.com/8533673/125362749-b73c7600-e36f-11eb-994b-3daf311dc28e.png)

**Comment by Ni3kjm** [comment]
Loving this card thanks, any way to set so different units are used if values exceed set amount to avoid the logger value overlap? E.g. Changing to show value in kW instead of W where I use for solar generation or grid use

**Comment by ziermmar** [comment]
> * set precision of displayed number in label (this is what I basically would want the most 😄 )
> 
> If I could set precision to 0.1 (1 digit after comma) it would fit, or make the label stacked vertically 

Take a look at my Pull Request for that feature (#70)
