### ISSUE TITLE
Customising CSS

### ISSUE THREAD

**Issue by Denyerec** [custom-cards/dual-gauge-card#40]
Apologies if this isn't the right place to ask, but I wanted to tweak the font sizing on the gauge so I edited www\community\dual-gauge-card\dual-gauge-card.js , saved it, and added a new card to my dashboard - However the changes didn't reflect in the card that appeared.

Is the JS file cached somehow by HA and stored elsewhere? I've been digging around trying to find out what's going on but it's a little opaque when it comes to exactly how card js is internalised by Lovelace so any pointers are greatly appreciated!

**Comment by Rocka84** [comment]
It's your Browser that caches resources.  
I'm sorry but I can't help much more with this. But I'm sure the fine folks over at the [Home Assistant Community](https://community.home-assistant.io/) can.
