### ISSUE TITLE
Card not working in HA 0.116

### ISSUE THREAD

**Issue by kaizersoje** [custom-cards/dual-gauge-card#41]
The card has stopped working after upgrading to version 0.116.

**Comment by frederickjh** [comment]
I think it stopped working before that. I have HA version 0.115.6 and when I install it with HACS it no longer appears in LoveLace as a card that can be added.

**Comment by frederickjh** [comment]
The release notes for the current version 5.2 say:
> fixed issues with Home Assistant 0.106 and newer
That release was on the 23rd of April. Version 0.108.8 was released on the 22nd of April. So I am guessing that somewhere after 0.108.8 this broke.
