### ISSUE TITLE
No card type found

### ISSUE THREAD

**Issue by robbrown92** [custom-cards/dual-gauge-card#46]
installed via hacs and added to repository and also tried adding direct to yaml

**Comment by myca5a** [comment]
Hello
The same issue ! 
However I have files in /config/www/community/dual-gauge-card

**Comment by DrNam1225** [comment]
I also have the same issue.

**Comment by DrNam1225** [comment]
Check if you added "url" in ui-lovelace.yaml.

  - url: /community_plugin/dual-gauge-card/dual-gauge-card.js
    type: js

**Comment by rybackisback** [comment]
I am having the same issue. Unable to configure card via manual custom card.

under 
resources: /hacsfiles/dual-gauge-card/dual-gauge-card.js and 
resources: javascript module.

**Comment by myca5a** [comment]
No change

**Comment by asifkassam** [comment]
same problem for me

**Comment by saper-2** [comment]
Hello,

I got the same issue and I was thinking it's not being loaded, but it loads (web browser dev tools show that the js is being loaded with HTTP/200 OK). The dual-gauge-card won't show up in the card list - you have to enter it's code manually 😞 ...

1. copy the ```dual-gauge-card.js``` into ```config/www/``` , 
2. Next add resource, go to config -> Lovelace Dashborads -> tab Resources, 
3. click *Add Resource*
4. Set fields: 
*url*: ```/local/dual-gauge-card.js```
*resource type*: ``JavaScript Module``` (should set automatically) 
(eventually adjust path to your HA system)
5. Now go to Dashboard that you want put the dual gauge,
6. From list of available cards at the very end there is button:  ```Need to add a custom card or just want to manually write the YAML?``` , use it. Should open editor, with empty ```type: ''```
Use the code as base, you have to adjust entities and other parameters to fit your need:
```
type: 'custom:dual-gauge-card'
title: Test 1
outer:
  entity: sensor.zewnatrz
  unit: °C
  min: -20
  max: 60
inner:
  entity: sensor.zewnatrz_2
  min: 0
  max: 100
  unit: '%'
```

Everything is down to manually edit card YAML and set type to ```custom:dual-gauge-card``` to get this card to work.

I guess this should be mentioned in README.md .

**Comment by DGF117** [comment]
Thanks for your solution !
