### ISSUE TITLE
Change value and title location

### ISSUE THREAD

**Issue by advertisingfree** [custom-cards/dual-gauge-card#49]
How can I put inner value to the left and outer value to the right? Also, how can I lower the title?

Thanks.

![image](https://user-images.githubusercontent.com/52855795/132082785-fd02d1b7-f3d9-4c2e-a138-387c9b59012f.png)

![image](https://user-images.githubusercontent.com/52855795/132082943-e30e0344-75e6-443c-b173-9ae34a3a2fdf.png)

**Comment by Rocka84** [comment]
Sorry, both isn't possible.
